TempData/Models/Team.cs
namespace TempData.Models
{
    public class Team
    {
        public int Id { get; set; }
        public string Position { get; set; }
        public string Image { get; set; }
        public ICollection<MediaTeam>? MediaTeams { get; set; }
    }
}

TempData/Areas/Admin/Controllers/TeamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TempData.Contexts;
using TempData.Helpers;
using TempData.Models;
using TempData.ViewModels.TeamVM;

namespace TempData.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeamController : Controller
    {
        public TeamController(TempDbContext db)
        {
            _db = db;
        }

        TempDbContext _db { get; }
        public async Task<IActionResult> Index()
        {
            var data = await _db.Teams.Select(s => new TeamListItemVM
            {
                Id=s.Id,
                Position=s.Position,
                Image=s.Image

            }).ToListAsync();
            return View(data);
        }
        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(TeamCreateVM vm)
        {
            if (!ModelState.IsValid) return View(vm);
            Team team = new Team
            {
                Position=vm.Position,
                Image=await vm.Image.SaveAsync(PathConst.Image)
            };
            await _db.Teams.AddAsync(team);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _db.Teams.FindAsync(id);
            if (data == null) return NotFound();
            _db.Teams.Remove(data);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();
            var data = await _db.Teams.FindAsync(id);
            if (data == null) return NotFound();
            return View(new TeamUpdateVM
            {
                Position=data.Position

            });

        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int? id,TeamUpdateVM vm)
        {
            if (id == null) return BadRequest();
            var data = await _db.Teams.FindAsync(id);
            if (data == null) return NotFound();
            data.Position = vm.Position;
            data.Image = await vm.Image.SaveAsync(PathConst.Image);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

TempData/Areas/Admin/Views/Team/Create.cshtml
@model TeamCreateVM
@{
    ViewData["Title"] = "Create";
}

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Position"></label>
        <input asp-for="Position" class="form-control" id="exampleInputEmail1" placeholder="Enter position">
        <span asp-validation-for="Position" class="form-text text-muted"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control" id="exampleInputEmail1" placeholder="Enter photo">
        <span asp-validation-for="Image" class="form-text text-muted"></span>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

TempData/Areas/Admin/Views/Team/Index.cshtml
@model List<TeamListItemVM>
@{
    ViewData["Title"] = "Index";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Team</h6>
        <a href="~/Admin/Team/Create" class="btn btn-primary">Create</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Position</th>
                        <th>Image</th>
                        <th colspan="2" class="text-center">Actions</th>
                        
                    </tr>
                </thead>
                @foreach(var item in Model)
                {
                    <tbody>
                        <td>@item.Id</td>
                        <td>@item.Position</td>
                        <td><img width="100px" src="~/@item.Image" /></td>
                        <td class="text-center"><a class="btn btn-outline-success" asp-action="Update" asp-controller="Team" asp-route-id="@item.Id">Update</a></td>
                    <td class="text-center"><a class="btn btn-outline-success" asp-action="Delete" asp-controller="Team" asp-route-id="@item.Id">Delete</a></td>

                    </tbody>
                }
            </table>
        </div>
    </div>
</div>

TempData/Areas/Admin/Views/Team/Update.cshtml
@model TeamUpdateVM
@{
    ViewData["Title"] = "Update";
}

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Position"></label>
        <input asp-for="Position" class="form-control" id="exampleInputEmail1" placeholder="Enter position">
        <span asp-validation-for="Position" class="form-text text-muted"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image"></label>
        <input asp-for="Image" class="form-control" id="exampleInputEmail1" placeholder="Enter photo">
        <span asp-validation-for="Image" class="form-text text-muted"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>